version: '3'
services:
  mahe-faerec:
    build: .
    image: fr_server_image
    container_name: compunnel_fr_server
    restart: always
    network_mode: "host"
    ports:
      - "5105:5105"

    # extra_hosts:
    # - "host.docker.internal:host-gateway"

    
    volumes:
      - ./:/recognize/

    # privileged: true

    command: 
      -  /bin/bash
      -  -c
      -  |

          cd /recognize/
          export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
          # python3.7 debug_server.py
          i=0
          while true
          do
            sleep 5
            ((i++))
          done
